# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.9.2'

## Part 1 - Data Preprocessing

### Importing the dataset

In [3]:
dataset = pd.read_csv('processed.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)

[[ 12.         15.          1.        ...  41.2       -37.8134078
  144.9794923]
 [ 12.         15.          1.        ...  48.3       -37.813073
  144.9804061]
 [ 12.         15.          1.        ...  44.8       -37.8149218
  144.9822582]
 ...
 [  6.          4.          4.        ...  52.2       -37.8195002
  144.9418888]
 [  6.          4.          6.        ...  52.2       -37.8195002
  144.9418888]
 [  6.          4.          6.        ...  52.4       -37.8195002
  144.9418888]]


In [5]:
print(y)

['Need irrigation' 'Need irrigation' 'Need irrigation' ...
 'Does not need irrigation' 'Does not need irrigation'
 'Does not need irrigation']


### Encoding categorical data

Label Encoding the "result" column

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [7]:
print(y)

[[ 12.         15.          1.        ...  41.2       -37.8134078
  144.9794923]
 [ 12.         15.          1.        ...  48.3       -37.813073
  144.9804061]
 [ 12.         15.          1.        ...  44.8       -37.8149218
  144.9822582]
 ...
 [  6.          4.          4.        ...  52.2       -37.8195002
  144.9418888]
 [  6.          4.          6.        ...  52.2       -37.8195002
  144.9418888]
 [  6.          4.          6.        ...  52.4       -37.8195002
  144.9418888]]


One Hot Encoding the "Longitude" and "Latitude" column

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [7, 8])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[ 0.   0.   0.  ... 21.6 96.4 41.2]
 [ 0.   0.   0.  ... 23.2 93.5 48.3]
 [ 0.   0.   0.  ... 21.6 97.2 44.8]
 ...
 [ 0.   0.   0.  ...  6.1  7.2 52.2]
 [ 0.   0.   0.  ...  5.8  7.3 52.2]
 [ 0.   0.   0.  ...  5.8  7.3 52.4]]


### Splitting the dataset into the Training set and Test set

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [12]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [13]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [14]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [15]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [16]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [17]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
1415/1415 [==============================] - 4s 2ms/step - loss: 0.3319 - accuracy: 0.8745
Epoch 2/100
1415/1415 [==============================] - 3s 2ms/step - loss: 0.1809 - accuracy: 0.9608
Epoch 3/100
1415/1415 [==============================] - 3s 2ms/step - loss: 0.1517 - accuracy: 0.9665
Epoch 4/100
1415/1415 [==============================] - 3s 2ms/step - loss: 0.1333 - accuracy: 0.9690
Epoch 5/100
1415/1415 [==============================] - 3s 2ms/step - loss: 0.1190 - accuracy: 0.9701
Epoch 6/100
1415/1415 [==============================] - 3s 2ms/step - loss: 0.1083 - accuracy: 0.9710
Epoch 7/100
1415/1415 [==============================] - 3s 2ms/step - loss: 0.1004 - accuracy: 0.9709
Epoch 8/100
1415/1415 [==============================] - 3s 2ms/step - loss: 0.0957 - accuracy: 0.9708
Epoch 9/100
1415/1415 [==============================] - 3s 2ms/step - loss: 0.0921 - accuracy: 0.9713
Epoch 10/100
1415/1415 [==============================] - 3s 2ms/step - l

## Part 4 - Making the predictions and evaluating the model

### Predicting the Test set results

In [18]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

354/354 [==============================] - 1s 1ms/step
[[1 1]
 [1 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [1 1]]


### Making the Confusion Matrix

In [19]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[5935  131]
 [ 146 5102]]


0.9755170585115785